version: 2
jobs:
  build:
    working_directory: ~/parabuzzle/craneoperator
    machine: true
    steps:
    - checkout
    - run:
        working_directory: ~/parabuzzle/craneoperator
        command: 'sudo docker info >/dev/null 2>&1 || sudo service docker start; '
    - restore_cache:
        keys:
        - dep-cache-{{ .Branch }}-
    # Setup environment
    - run: docker info
    - run: gem install httparty
    - run: gem install memoist
    - run: npm install

    # Build bundle
    - run: npm install webpack

    # Build docker image
    - run: rake build

    # Save dependency cache
    - save_cache:
        key: dep-cache-{{ .Branch }}
        paths:
        # This is a broad list of cache paths to include many possible development environments
        # You can probably delete some of these entries
        - vendor/bundle
        - ~/.bundle
        - ./node_modules

    # Test
    #   This would typically be a build job when using workflows, possibly combined with build
    # This is based on your 1.0 configuration file or project settings
    - run: docker run -d -p 80:80 parabuzzle/craneoperator:latest; sleep 10
    - run: curl --retry 10 --retry-delay 5 -v http://localhost/

  deploy:
    machine:
        enabled: true
    working_directory: ~/parabuzzle/craneoperator
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: rake push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master